### ISSUE TITLE
Questions for JP

### ISSUE THREAD

**Issue by ChantalForget** [sstone93/MAGIC#68]
@michaelcatt @SunsetBlade @sstone93 
- [x] what does he want for treasures?
- [x] how the activities work with networking, because we implemented the actual way of using activities

**Comment by SunsetBlade** [comment]
I went ahead and spoke to JP during his office hours today and got these questions answered so here goes:
1. For treasures he wants exactly what we already have. Each unique treasure is instantiated and has a set gold value. If we happen to have defined the unique properties of an item, (As we will) then that just goes on top.
2. What he means by simultaneous play in the topmost tier of features, is a deliberate divergence from the rules. For this, the game would become very similar to a traditional online multi-player game. All players experience the day simultaneously, and submit moves one at a time. A submitted move is immediately acted upon and the map is updated for all clients (ideally with no latency) to reflect the new game state.
